"""Markdown formatter for paper digest PRs."""

from __future__ import annotations

from .paper_fetcher import Paper


def format_paper_pr_body(paper: Paper, summary: str, date_label: str) -> str:
    """Format the PR body for a paper digest."""
    authors_str = ", ".join(paper.authors[:5])
    if len(paper.authors) > 5:
        authors_str += f" 他{len(paper.authors) - 5}名"

    lines = [
        f"# 📄 Paper Digest: {date_label}",
        "",
        f"## {paper.title}",
        "",
        "| 項目 | 詳細 |",
        "|------|------|",
        f"| **著者** | {authors_str} |",
        f"| **発表日** | {paper.published or '不明'} |",
        f"| **分野** | {paper.category_ja} |",
        f"| **arXiv** | [リンク]({paper.url}) |",
    ]

    if paper.pdf_url:
        lines.append(f"| **PDF** | [リンク]({paper.pdf_url}) |")

    lines.extend([
        "",
        "---",
        "",
        summary,
        "",
        "---",
        f"Auto-generated by Paper Digest workflow. Category: {paper.category_ja}",
    ])

    return "\n".join(lines)
