"""Git operations and PR creation using gh CLI."""

from __future__ import annotations

import logging
import pathlib
import subprocess

logger = logging.getLogger(__name__)


def _run(cmd: list[str], cwd: str | pathlib.Path | None = None) -> subprocess.CompletedProcess:
    """Run a shell command and return the result."""
    logger.debug("Running: %s", " ".join(cmd))
    return subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)


def create_pr(
    briefing_path: pathlib.Path,
    week_label: str,
    article_count: int = 0,
    repo_root: str | pathlib.Path | None = None,
    briefing: str = "",
) -> str | None:
    """Create a branch, commit the briefing file, and open a PR.

    Returns the PR URL on success, None on failure.
    """
    branch_name = f"digest/{week_label}"
    cwd = str(repo_root) if repo_root else None

    # Check if branch already exists on remote
    result = _run(["git", "ls-remote", "--heads", "origin", branch_name], cwd=cwd)
    if result.stdout.strip():
        logger.warning("Branch %s already exists on remote, skipping", branch_name)
        return None

    # Create and switch to new branch
    result = _run(["git", "checkout", "-b", branch_name], cwd=cwd)
    if result.returncode != 0:
        logger.error("Failed to create branch: %s", result.stderr)
        return None

    try:
        # Stage briefing file
        _run(["git", "add", str(briefing_path)], cwd=cwd)

        # Commit
        commit_msg = f"Add weekly briefing: {week_label}"
        result = _run(["git", "commit", "-m", commit_msg], cwd=cwd)
        if result.returncode != 0:
            logger.error("Failed to commit: %s", result.stderr)
            return None

        # Push
        result = _run(["git", "push", "-u", "origin", branch_name], cwd=cwd)
        if result.returncode != 0:
            logger.error("Failed to push: %s", result.stderr)
            return None

        # Build PR body
        pr_body = _build_pr_body(week_label, article_count, briefing)

        # Create PR
        result = _run(
            [
                "gh", "pr", "create",
                "--title", f"Weekly Digest: {week_label}",
                "--body", pr_body,
                "--base", "main",
                "--reviewer", "yuhi-sa",
            ],
            cwd=cwd,
        )
        if result.returncode != 0:
            logger.error("Failed to create PR: %s", result.stderr)
            return None

        pr_url = result.stdout.strip()
        logger.info("PR created: %s", pr_url)
        return pr_url

    finally:
        # Switch back to main branch
        _run(["git", "checkout", "main"], cwd=cwd)


def _build_pr_body(
    week_label: str,
    article_count: int,
    briefing: str = "",
) -> str:
    """Build the PR description body."""
    lines = [
        f"## Weekly News Digest: {week_label}",
        "",
        f"- **Total articles this week**: {article_count}",
    ]

    if briefing:
        lines.extend(["", "---", ""])
        lines.append(briefing)

    lines.extend([
        "",
        "---",
        "Auto-generated by Weekly News Digest workflow.",
    ])
    return "\n".join(lines)
